Import Library

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report

In [2]:
df= pd.read_csv(r".\Titanic-Dataset.csv")

EDA

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

removing 'Cabin' column due to have more number of null values and the data it contains is nominal which will not be treated

In [11]:
df = df.drop(['PassengerId','Cabin','Name','Ticket'],axis=1)

In [17]:
df.replace({'Sex':{'male':1,'female':0},
             'Embarked':{'S':0,'C':1,'Q':2}
           },inplace=True)

C:\Users\Soham\AppData\Local\Temp\ipykernel_11500\1662327362.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'Sex':{'male':1,'female':0},

In [19]:
df

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500       0.0
1           1       1    0  38.0      1      0  71.2833       1.0
2           1       3    0  26.0      0      0   7.9250       0.0
3           1       1    0  35.0      1      0  53.1000       0.0
4           0       3    1  35.0      0      0   8.0500       0.0
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    1  27.0      0      0  13.0000       0.0
887         1       1    0  19.0      0      0  30.0000       0.0
888         0       3    0   NaN      1      2  23.4500       0.0
889         1       1    1  26.0      0      0  30.0000       1.0
890         0       3    1  32.0      0      0   7.7500       2.0

[891 rows x 8 columns]

Treating null values

In [22]:
df.fillna({'Age':df['Age'].mean()},inplace=True) #filling nan value with the mean as it is numerical column
df.fillna({'Embarked':df['Embarked'].mode()[0]},inplace=True) #filling nan value with mode as it is categorical column

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    float64
dtypes: float64(3), int64(5)
memory usage: 55.8 KB

preparing data for spliting data in train and test

In [28]:
X= df.drop("Survived",axis=1)
y=df['Survived']

splitting the data in to train data and test data

In [31]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

training logistic regression model as it is a predictive classification problem

In [34]:
logistic_reg = LogisticRegression(max_iter=500)

In [36]:
logistic_reg.fit(X_train,y_train)

LogisticRegression(max_iter=500)

In [38]:
logistic_reg.score(X_train,y_train)

0.8025682182985554

testing the logistic reggression

In [41]:
y_pred = logistic_reg.predict(X_test)

Creating the classification report

In [44]:
confusion_matrix(y_test,y_pred)

array([[136,  21],
       [ 31,  80]], dtype=int64)

In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.87      0.84       157
           1       0.79      0.72      0.75       111

    accuracy                           0.81       268
   macro avg       0.80      0.79      0.80       268
weighted avg       0.81      0.81      0.80       268